apiVersion: apps/v1
kind: Deployment
metadata:
  name: StatusBoard
  labels:
    app: StatusBoard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: StatusBoard
  template:
    metadata:
      labels:
        app: StatusBoard
    spec:
      containers:
        - name: StatusBoard
          image: username/StatusBoard:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5